### ISSUE TITLE
【バグ】 Linux/Unix: player-info/monk-data-type not included in the result of "make dist"

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#1719]
## 環境

- OS: Debian 11
- バージョン: 3.0.0Alpha39 with commit c7f43a85e53fa112a3e935cb04bc55d8aa8e8c8c

## バグの詳細

Running "make DISTCHECK_CONFIGURE_FLAGS=--disable-japanese distcheck" fails after commit c7f43a85e53fa112a3e935cb04bc55d8aa8e8c8c .  The compiler error at the point of failure is

```
../../../src/hpmp/hp-mp-processor.cpp:26:10: fatal error: player-info/monk-data-type.h: No such file or directory
```

## 再現手順

Running the following at the top level of the Hengband's source files triggers the problem for me (I use --disable-worldscore since libcurl isn't currently installed on the system):

1. ./bootstrap
2. ./configure --disable-worldscore
3. make DISTCHECK_CONFIGURE_FLAGS="--disable-japanese --disable-worldscore" distcheck

Compiling normally works.  The problem is caused by monk-data-type.h not being included in the result of "make dist" so the subsequent compilation done by "make distcheck" fails.

## 期待される正常な動作

"make DISTCHECK_CONFIGURE_FLAGS=--disable-japanese distcheck" works as well as compiling normally.
