### PR TITLE
[Refactor] MonsterSweepGrid::mmを削除

### LINKED ISSUE #4992: 【バグ】 With Apple's clang 15, pointer arithmetic with incomplete type
## 環境

- OS: macOS 14.7.2 (GitHub runner for macos-latest)
- バージョン: 3.0.1Beta25 + changes up to dbcfea4b6d4518d5ca698daaa869fb18d4009286 + changes from https://github.com/backwardsEric/hengband for macOS

## バグの詳細

With Apple's clang 15 and Hengband configured with "./configure --disable-net --disable-worldscore", compilation fails for monster/floor/monster-direction.cpp with this error:

```
In file included from monster-floor/monster-direction.cpp:7:
In file included from ./monster-floor/monster-direction.h:4:
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/span:541:32: error: arithmetic on a pointer to an incomplete type 'Direction'
        return iterator(data() + size());
                        ~~~~~~ ^
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__ranges/access.h:150:36: note: in instantiation of member function 'std::span<Direction>::end' requested here
      return _LIBCPP_AUTO_CAST(__t.end());
                                   ^
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__ranges/concepts.h:49:5: note: in instantiation of function template specialization 'std::ranges::__end::__fn::operator()<const std::span<Direction> &>' requested here
    ranges::end(__t);
    ^
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__ranges/concepts.h:49:5: note: in instantiation of requirement here
    ranges::end(__t);
    ^~~~~~~~~~~~~~~~
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__ranges/concepts.h:47:19: note: while substituting template arguments into constraint expression here
  concept range = requires(_Tp& __t) {
                  ^~~~~~~~~~~~~~~~~~~~
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__ranges/concepts.h:53:25: note: while checking the satisfaction of concept 'range<const std::span<Direction> &>' requested here
  concept input_range = range<_Tp> && input_iterator<iterator_t<_Tp>>;
                        ^~~~~~~~~~
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__ranges/concepts.h:53:25: note: (skipping 11 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/span:442:15: note: while checking the satisfaction of concept '__span_compatible_range<const std::span<Direction> &, Direction>' requested here
    template <__span_compatible_range<element_type> _Range>
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/span:442:15: note: while substituting template arguments into constraint expression here
    template <__span_compatible_range<element_type> _Range>
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/span:391:28: note: while checking constraint satisfaction for template 'span<Direction>' required here
class _LIBCPP_TEMPLATE_VIS span<_Tp, dynamic_extent> {
                           ^~~~
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/span:391:28: note: in instantiation of function template specialization 'std::span<Direction>::span<const std::span<Direction> &>' requested here
./monster-floor/monster-sweep-grid.h:11:7: note: while declaring the implicit copy constructor for 'MonsterSweepGrid'
class MonsterSweepGrid {
      ^
./monster-floor/monster-direction.h:6:7: note: forward declaration of 'Direction'
class Direction;
      ^
```

## 再現手順

In the top-level directory of a checked out version of dbcfea4b6d4518d5ca698daaa869fb18d4009286 , run

1. ./bootstrap
2. ./configure --disable-net --disable-worldscore
3. make

## 期待される正常な動作

Compilation  is successful.

## 補足事項

Compilation does work with Apple's clang 14 on macOS 12.7.6.

As might be expected, including floor/geometry.h in monster-floor/monster-direction.cpp before monster-floor/monster-sweep-grid.h does resolve that compilation error.  Changing the order of the include files in monster-floor/monster-sweep-grid.cpp so monster-floor/monster-sweep-grid.h is included after floor/geometry.h avoids a similar compilation error with monster-floor/monster-sweep-grid.cpp.

### PR DESCRIPTION
**Pull request by habu1010**
Resolves #4992

Apple Clang 15で暗黙のコピーコンストラクタ宣言によりmmの型である`std::span<Direction>`においてDirection型の完全な型が必要となりコンパイル エラーが発生する。
mmをメンバで持たせるのがそもそも違和感があるので、メンバから削除しget_movable_grid()の引数として渡すようにする。

最終的にはモンスターの移動候補クラスのようなものにしたいが、複数の関数に範囲にわたって配列の参照を引き回しているため設計の見直しが必要となりそうなので、とりあえずコンパイルエラーを回避する暫定処置。

### CODE REVIEW

**Review by Hourier — APPROVED** [review]
対応お疲れ様です
特に問題ないかと思います
Approveします、設計改善引き続きよろしくお願いします

**Comment by habu1010** [comment]
確認ありがとうございました 🙇🏻
