### ISSUE TITLE
【バグ】 src/bot/bot-socket-server.cpp does not compile on macOS and OpenBSD

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#5523]
## 環境

- OS: macOS 26.6.1 and openBSD 7.9 for arm64
- バージョン: 3.0.2Beta4 + changes up to 4217f0db161993ceb0d619d949ce596f77f06b8d

## バグの詳細

src/bot/bot-socket-server.cpp does not compile on macOS 26.6.1 (running on an Apple M3 chip) and OpenBSD 7.9 for arm64.  The compiler errors on macOS using Apple's clang 21.0.0 (from Xcode 26.6) are:

```
bot/bot-socket-server.cpp:389:33: error: expected
      unqualified-id
  389 |     address.sin_addr.s_addr = ::htonl(INADDR_LOOPBACK);
      |                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_endian.h:137:25: note: 
      expanded from macro 'htonl'
  137 | #define htonl(x)        __DARWIN_OSSwapInt32(x)
      |                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libkern/_OSByteOrder.h:70:5: note: 
      expanded from macro '__DARWIN_OSSwapInt32'
   70 |     (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt32(x) : _OSSwapInt32(x))
      |     ^
bot/bot-socket-server.cpp:391:26: error: expected
      unqualified-id
  391 |     address.sin_port = ::htons(static_cast<uint16_t>(this->port));
      |                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_endian.h:134:25: note: 
      expanded from macro 'htons'
  134 | #define htons(x)        __DARWIN_OSSwapInt16(x)
      |                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libkern/_OSByteOrder.h:67:5: note: 
      expanded from macro '__DARWIN_OSSwapInt16'
   67 |     ((__uint16_t)(__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt16(x...
      |     ^
```

The errors on OpenBSD 7.9 with clang 19.1.7 are:

```
bot/bot-socket-server.cpp:389:33: error: expected unqualified-id
  389 |     address.sin_addr.s_addr = ::hotel(INADDR_LOOPBACK);
      |
/usr/include/sys/endian.h:96:18: note: expanded from macro 'htonl'
   96 | #define htonl(x).      __htobe32(x)
      |
/usr/include/sys//_endian.h:99:19: note: expanded from macro '__htobe32'
   99 | #define __htobe32       __swap32
      |
/usr/include/sys/_endian.h:89:2: note: expanded from macro '__swap32'
   89 |         (__uint32_t)(__builtin_constant_p(x) ? __swap32gen(x) : __swap32md(x))
      |
bot/bot-socket-server.cpp:389:33: error: unexpected type name '__uint32_t': expected expression
/usr/include/sys/endian.h:96:18: note: expanded from macro 'htonl'
   96 | #define htonl(x).      __htobe32(x)
      |
/usr/include/sys//_endian.h:99:19: note: expanded from macro '__htobe32'
   99 | #define __htobe32       __swap32
      |
/usr/include/sys/_endian.h:89:2: note: expanded from macro '__swap32'
   89 |         (__uint32_t)(__builtin_constant_p(x) ? __swap32gen(x) : __swap32md(x))
      |
bot/bot-socket-server.cpp:391:26: error: expected unqualified-id
  391 |     address.sin_port = ::tons(static_cast<uint16_t>(this->port));
      |
/usr/include/sys/endian.h:95:18: note: expanded from macro 'htons'
   95 | #define htons(x).      __htobe16(x)
      |
/usr/include/sys/_endian.h:98:19: note: expanded from macro '__htobe16'
   98 | #define __htobe16.      __swap16
      |
/usr/include/sys/_endian.h:87:2: note: expanded from macro '__swap16'
   87 |         (__uint16_t)(__builtin_constant_p(x) ? __swap16gen(x) : __swap16md(x)
      |
bot/bot-socket-server.cpp:391:26: error: unexpected type name '__uint16t': expected expression
  391 |     address.sin_port = ::tons(static_cast<uint16_t>(this->port));
      |
/usr/include/sys/endian.h:95:18: note: expanded from macro 'htons'
   95 | #define htons(x).      __htobe16(x)
      |
/usr/include/sys/_endian.h:98:19: note: expanded from macro '__htobe16'
   98 | #define __htobe16.      __swap16
      |
/usr/include/sys/_endian.h:87:2: note: expanded from macro '__swap16'
   87 |         (__uint16_t)(__builtin_constant_p(x) ? __swap16gen(x) : __swap16md(x)
      |
```

## 再現手順

On macOS with Xcode 26.6, autoconf 2.72, automake 1.18, and m4 1.4.20 installed, run the following in the top level of the source tree:

1. ./bootstrap
2. ./configure --disable-japanese --disable-net
3. make

On OpenBSD 7.9 for arm64 with autoconf 2.72p0, automake 1.18.1, and gmake 4.4.1p0 installed ('pkg_add autoconf-2.72p0 automake-1.18.1 gmake-4.4.1p0'), do the following in the top level of the source tree:

1. Edit src/system/angband-system.h to add two lines, '#undef major' and '#undef minor', immediately after '#include <string.h>'.  That works around that major() and minor() are macros defined in sys/types.h for extracting the major and minor parts from a device number.
2. Run 'env AUTOMAKE_VERSION=1.18 AUTOCONF_VERSION=2.72 ./bootstrap'
3. Run './configure --disable-japanese --disable-net'
4. Run 'gmake'.

## 期待される正常な動作

bot/bot-socket-server.cpp compiles without errors.

## 補足事項

To avoid the compilation errors on macOS, I inserted this immediately after '#include <fmt/format.h>' in src/bot/bot-sockert-server.cpp:

```
/*
 * macOS has htons() and htonl() as macros that fail when invoked as ::htons
 * and ::htonl.  Work around that.
 */
#if defined(__APPLE__) && defined(__MACH__)
#define my_htons(x) htons(x)
#define my_htonl(x) htonl(x)
#else
#define my_htons(x) ::htons(x)
#define my_htonl(x) ::htonl(x)
#endif
```

And then called my_htons() and my_htonl() later on in the file rather than ::htons() and ::htonl(), respectively.  If something similar was to be used for OpenBSD or other platforms that have much the same problem, it would presumably be better to test whether ::htons() and ::htonl() do not compile (but htons() and htonl() do) in the configuration step and set a preprocessor macro based on that which is tested for in src/bot/bot-socket-server.cpp.

**Comment by habu1010** [comment]
Thanks for the detailed report — the error output and the reproduction steps made this straightforward to track down. I've opened #5524, which addresses both of the problems you ran into.

### 1. `::htonl()` / `::htons()`

Instead of special-casing `__APPLE__` (or adding a configure check), I just dropped the `::` qualifier.

`htonl`/`htons` are function-like macros on many platforms, and the preprocessor expands `htonl(` regardless of the preceding `::`, so the expansion lands immediately after the `::`:

| Platform | `htonl(x)` expands to | Result |
| --- | --- | --- |
| Linux/glibc | `__bswap_32 (x)`, where `__bswap_32` is an inline **function** | `::__bswap_32(x)` — happens to compile |
| macOS | `__DARWIN_OSSwapInt32(x)`, itself a macro | `::(__builtin_constant_p(x) ? …)` — syntax error |
| OpenBSD | `__htobe32(x)` → `__swap32(x)`, itself a macro | same as above |

In other words, the `::` was wrong to begin with, and it only ever compiled on glibc by accident. Calling them unqualified is correct whether the platform provides them as macros or as functions, and it needs no platform conditionals that would have to grow for NetBSD, FreeBSD, and so on. I left a comment at the call site explaining why these two calls are unqualified while the surrounding socket calls are not.

### 2. `major()` / `minor()`

I also fixed the `sys/types.h` conflict you had to work around by hand, so step 1 of your OpenBSD reproduction should no longer be necessary.

Since function-like macros only expand when the identifier is directly followed by `(`, declarations such as `uint8_t major = 0;` and references such as `version.major` are unaffected. The only place in the whole tree that actually breaks is the member initializer list of `AngbandVersion` in `src/system/angband-version.h`:

```cpp
AngbandVersion(uint8_t major, uint8_t minor, uint8_t patch, uint8_t extra)
    : major(major)   // "major(" expands here
    , minor(minor)
```

Rather than `#undef`-ing the macros (which takes the real API away from the rest of the translation unit) or renaming the members, I removed the constructors and made `AngbandVersion` an aggregate, which eliminates the `major(` token sequence entirely. Every existing use — `AngbandVersion{}` and `set_version({ major, minor, patch, extra })` — keeps working unchanged.

### Verification

I don't have macOS or OpenBSD hardware, so on my side this is limited to a Linux build plus a small translation unit that mimics the Darwin/OpenBSD macro definitions: the old code reproduces both errors there and the new code compiles. I also confirmed the control server still listens and responds, and that an existing save file still loads.

Could you try building `develop` with #5524 applied on both of your machines, **without any local edits**, and let me know whether it goes through? If anything else turns up, I'd be glad to hear about it.

**Comment by habu1010** [comment]
@backwardsEric 
tagging for notification
