### PR TITLE
[Fix] macOS / OpenBSD でコンパイルできない問題を修正

### LINKED ISSUE #5523: 【バグ】 src/bot/bot-socket-server.cpp does not compile on macOS and OpenBSD
## 環境

- OS: macOS 26.6.1 and openBSD 7.9 for arm64
- バージョン: 3.0.2Beta4 + changes up to 4217f0db161993ceb0d619d949ce596f77f06b8d

## バグの詳細

src/bot/bot-socket-server.cpp does not compile on macOS 26.6.1 (running on an Apple M3 chip) and OpenBSD 7.9 for arm64.  The compiler errors on macOS using Apple's clang 21.0.0 (from Xcode 26.6) are:

```
bot/bot-socket-server.cpp:389:33: error: expected
      unqualified-id
  389 |     address.sin_addr.s_addr = ::htonl(INADDR_LOOPBACK);
      |                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_endian.h:137:25: note: 
      expanded from macro 'htonl'
  137 | #define htonl(x)        __DARWIN_OSSwapInt32(x)
      |                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libkern/_OSByteOrder.h:70:5: note: 
      expanded from macro '__DARWIN_OSSwapInt32'
   70 |     (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt32(x) : _OSSwapInt32(x))
      |     ^
bot/bot-socket-server.cpp:391:26: error: expected
      unqualified-id
  391 |     address.sin_port = ::htons(static_cast<uint16_t>(this->port));
      |                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_endian.h:134:25: note: 
      expanded from macro 'htons'
  134 | #define htons(x)        __DARWIN_OSSwapInt16(x)
      |                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libkern/_OSByteOrder.h:67:5: note: 
      expanded from macro '__DARWIN_OSSwapInt16'
   67 |     ((__uint16_t)(__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt16(x...
      |     ^
```

The errors on OpenBSD 7.9 with clang 19.1.7 are:

```
bot/bot-socket-server.cpp:389:33: error: expected unqualified-id
  389 |     address.sin_addr.s_addr = ::hotel(INADDR_LOOPBACK);
      |
/usr/include/sys/endian.h:96:18: note: expanded from macro 'htonl'
   96 | #define htonl(x).      __htobe32(x)
      |
/usr/include/sys//_endian.h:99:19: note: expanded from macro '__htobe32'
   99 | #define __htobe32       __swap32
      |
/usr/include/sys/_endian.h:89:2: note: expanded from macro '__swap32'
   89 |         (__uint32_t)(__builtin_constant_p(x) ? __swap32gen(x) : __swap32md(x))
      |
bot/bot-socket-server.cpp:389:33: error: unexpected type name '__uint32_t': expected expression
/usr/include/sys/endian.h:96:18: note: expanded from macro 'htonl'
   96 | #define htonl(x).      __htobe32(x)
      |
/usr/include/sys//_endian.h:99:19: note: expanded from macro '__htobe32'
   99 | #define __htobe32       __swap32
      |
/usr/include/sys/_endian.h:89:2: note: expanded from macro '__swap32'
   89 |         (__uint32_t)(__builtin_constant_p(x) ? __swap32gen(x) : __swap32md(x))
      |
bot/bot-socket-server.cpp:391:26: error: expected unqualified-id
  391 |     address.sin_port = ::tons(static_cast<uint16_t>(this->port));
      |
/usr/include/sys/endian.h:95:18: note: expanded from macro 'htons'
   95 | #define htons(x).      __htobe16(x)
      |
/usr/include/sys/_endian.h:98:19: note: expanded from macro '__htobe16'
   98 | #define __htobe16.      __swap16
      |
/usr/include/sys/_endian.h:87:2: note: expanded from macro '__swap16'
   87 |         (__uint16_t)(__builtin_constant_p(x) ? __swap16gen(x) : __swap16md(x)
      |
bot/bot-socket-server.cpp:391:26: error: unexpected type name '__uint16t': expected expression
  391 |     address.sin_port = ::tons(static_cast<uint16_t>(this->port));
      |
/usr/include/sys/endian.h:95:18: note: expanded from macro 'htons'
   95 | #define htons(x).      __htobe16(x)
      |
/usr/include/sys/_endian.h:98:19: note: expanded from macro '__htobe16'
   98 | #define __htobe16.      __swap16
      |
/usr/include/sys/_endian.h:87:2: note: expanded from macro '__swap16'
   87 |         (__uint16_t)(__builtin_constant_p(x) ? __swap16gen(x) : __swap16md(x)
      |
```

## 再現手順

On macOS with Xcode 26.6, autoconf 2.72, automake 1.18, and m4 1.4.20 installed, run the following in the top level of the source tree:

1. ./bootstrap
2. ./configure --disable-japanese --disable-net
3. make

On OpenBSD 7.9 for arm64 with autoconf 2.72p0, automake 1.18.1, and gmake 4.4.1p0 installed ('pkg_add autoconf-2.72p0 automake-1.18.1 gmake-4.4.1p0'), do the following in the top level of the source tree:

1. Edit src/system/angband-system.h to add two lines, '#undef major' and '#undef minor', immediately after '#include <string.h>'.  That works around that major() and minor() are macros defined in sys/types.h for extracting the major and minor parts from a device number.
2. Run 'env AUTOMAKE_VERSION=1.18 AUTOCONF_VERSION=2.72 ./bootstrap'
3. Run './configure --disable-japanese --disable-net'
4. Run 'gmake'.

## 期待される正常な動作

bot/bot-socket-server.cpp compiles without errors.

## 補足事項

To avoid the compilation errors on macOS, I inserted this immediately after '#include <fmt/format.h>' in src/bot/bot-sockert-server.cpp:

```
/*
 * macOS has htons() and htonl() as macros that fail when invoked as ::htons
 * and ::htonl.  Work around that.
 */
#if defined(__APPLE__) && defined(__MACH__)
#define my_htons(x) htons(x)
#define my_htonl(x) htonl(x)
#else
#define my_htons(x) ::htons(x)
#define my_htonl(x) ::htonl(x)
#endif
```

And then called my_htons() and my_htonl() later on in the file rather than ::htons() and ::htonl(), respectively.  If something similar was to be used for OpenBSD or other platforms that have much the same problem, it would presumably be better to test whether ::htons() and ::htonl() do not compile (but htons() and htonl() do) in the configuration step and set a preprocessor macro based on that which is tested for in src/bot/bot-socket-server.cpp.

### PR DESCRIPTION
**Pull request by habu1010**
## 概要

#5523 で報告された、macOS 26.6.1 (Apple clang 21) および OpenBSD 7.9/arm64 (clang 19.1.7) で
コンパイルできない問題を修正します。

原因は独立した 2 つで、それぞれ 1 コミットに分けています。

## 修正1: `::htonl()` / `::htons()`

`src/bot/bot-socket-server.cpp` が `::htonl()` / `::htons()` とスコープ解決演算子付きで呼んでいました。

`htonl`/`htons` は多くの環境で**関数ではなく関数形式マクロ**です。プリプロセッサは直前の `::` を
無視して展開するため、展開結果が `::` の直後に来ます。

| 環境 | `htonl(x)` の展開 | 結果 |
| --- | --- | --- |
| Linux/glibc | `__bswap_32 (x)` (`__bswap_32` は inline **関数**) | `::__bswap_32(x)` となり偶然通る |
| macOS | `__DARWIN_OSSwapInt32(x)` → 更にマクロ | `::(__builtin_constant_p(x) ? …)` で `expected unqualified-id` |
| OpenBSD | `__htobe32(x)` → `__swap32(x)` → 更にマクロ | 同上 |

Linux で通っていたのは実装依存の偶然で、`::` を付けること自体が誤りでした。
**修飾を外せばマクロ実装・関数実装のどちらの環境でも正しく動く**ため、そのようにしています。
プラットフォーム分岐も configure での検査も不要です。

このファイルは他の OS API を `::socket()` `::bind()` `::recv()` … と `::` 付きで統一しているため、
なぜここだけ修飾が無いのかをコメントで明記しました。

## 修正2: `major()` / `minor()` マクロとの衝突

こちらは #5518 とは無関係の既存問題ですが、#5523 の再現手順で
「OpenBSD では `#undef major` / `#undef minor` を足す前作業が必要」と報告されているため併せて直します。

OpenBSD 等の `sys/types.h` は `major()` / `minor()` をデバイス番号を分解する関数形式マクロとして
定義しており、これが `AngbandVersion` のコンストラクタのメンバ初期化子と衝突します。

```cpp
AngbandVersion(uint8_t major, uint8_t minor, uint8_t patch, uint8_t extra)
    : major(major)   // ← "major(" が展開されてコンパイルエラー
    , minor(minor)
```

関数形式マクロは識別子の直後が `(` のときだけ展開されるため、メンバ宣言 `uint8_t major = 0;` や
参照 `version.major`、引数宣言 `h_older_than(uint8_t major, …)` は無害です。
コードベース全体で `major(` / `minor(` の形になっているのはこの 2 行だけでした。

`#undef` は OS の API をプリプロセッサで潰す副作用があり、メンバ名の改名は参照側 10 数箇所に
波及するため、いずれも採らず、**コンストラクタを削除して集成体 (aggregate) にする**ことで
`major(` というトークン列自体を無くしました。全メンバが public でデフォルトメンバ初期化子を
持つため、既存の使い方はそのまま通ります。

- `AngbandVersion version{};` → 集成体の値初期化で全メンバ 0
- `set_version({ major, minor, patch, extra });` → 集成体初期化

再発防止として、その旨をクラスのコメントに残しています。

## 動作確認

- Linux (g++) でのビルド: 成功
- macOS / OpenBSD 流のマクロ定義を模した TU での構文チェック: 修正前は両方の箇所が同じエラーを
  再現し、修正後は通過することを確認
- 制御サーバの実動作: `--headless --control-port=<port>` で待ち受けが張れ、`info` / `screen` が
  正常に応答することを確認
- セーブデータのロード: 既存のセーブファイルを読み込んでプレイ画面まで到達することを確認
  (集成体初期化になった `set_version()` の経路とロード中のバージョン比較を通過)

macOS / OpenBSD の実機は手元に無いため、最終確認は報告者にお願いできればと思います。

Fixes #5523

🤖 Generated with [Claude Code](https://claude.com/claude-code)

## Summary by CodeRabbit

- **バグ修正**
  - 特定の環境で発生していたコンパイル上の互換性問題を修正しました。
  - バージョン情報の扱いを整理し、環境によって発生する名前の衝突を回避しました。

- **改善**
  - 通信設定およびバージョン情報の初期化方法を見直し、ビルドの安定性を向上させました。

### CODE REVIEW

**Comment by backwardsEric** [comment]
I merged in this pull request into the current head of the develop branch.  Compiling that on MacOS 26.6.1 and OpenBSD 7.9 for arm64 was free from the errors mentioned in https://github.com/hengband/hengband/issues/5523 .

**Review by Slimebreath6078 — APPROVED** [review]
修正内容確認しました
Approve いたします

**Comment by habu1010** [comment]
確認ありがとうございました🙇
