### ISSUE TITLE
【バグ】 Linux/Unix:  make distcheck fails with commit c5c5a89464148c47a067be5782495b8a57c4b68a

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#1646]
## 環境

- OS: Debian 11
- バージョン: 3.0.0Alpha39 after commit c5c5a89464148c47a067be5782495b8a57c4b68a

## バグの詳細

On Debian 11, running

```
./bootstrap
./configure --disable-worldscore --disable-japanese
make DISTCHECK_CONFIGURE_FLAGS="--disable-worldscore --disable-japanese"
```

in the top-level directory for Hengband fails.  The message at the point of the failure is

```
../../../src/load/player-class-specific-data-loader.cpp:3:10: fatal error: player-info/bard-data-type.h: No such file or directory
```

The failure only happens with "make distcheck"; normal compilations work.  bard-data-type.h isn't being copied to the temporary tar ball that's used as the basis for compilation with "make distcheck".

## 期待される正常な動作

The expected behavior is that "make DISTCHECK_CONFIGURE_FLAGS=--disable-japanese distcheck" works as well as a normal compilation.
