### ISSUE TITLE
【バグ】 Linux/Unix: make distcheck fails with commit 462ff4c1148c790be134e461e498b8d27f4c1337

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#1631]
## 環境

- OS: Debian 11
- バージョン: 3.0.0Alpha39 after commit 462ff4c1148c790be134e461e498b8d27f4c1337

## バグの詳細

On Debian 11, running

```
./bootstrap
./configure --disable-worldscore --disable-japanese
make DISTCHECK_CONFIGURE_FLAGS="--disable-worldscore --disable-japanese" distcheck
```

in the top-level directory for Hengband fails.  The message at the point of the failure is

```
In file included from ../../../src/action/action-limited.cpp:15:
../../../src/sytem/player-type-definition.h:7:10: fatal error: player-info/class-specific-data.h: No such file or directory
```

The failure only happens with "make distcheck"; normal compilations work.  class-specific-data.h isn't being copied to the temporary tarball that's used as the basis for the compilation with "make distcheck".

## 期待される正常な動作

The expected behavior is that "make DISTCHECK_CONFIGURE_FLAGS=--disable-japanese distcheck" works as well as a normal compilation.
